python3 randomized_parameter_frag_create.py --mass 200 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 300 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 350 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 400 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 500 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 600 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 700 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 800 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 900 --proc cgbh
python3 randomized_parameter_frag_create.py --mass 200 --proc bgth
python3 randomized_parameter_frag_create.py --mass 300 --proc bgth
python3 randomized_parameter_frag_create.py --mass 350 --proc bgth
python3 randomized_parameter_frag_create.py --mass 400 --proc bgth
python3 randomized_parameter_frag_create.py --mass 500 --proc bgth
python3 randomized_parameter_frag_create.py --mass 600 --proc bgth
python3 randomized_parameter_frag_create.py --mass 700 --proc bgth
python3 randomized_parameter_frag_create.py --mass 800 --proc bgth
python3 randomized_parameter_frag_create.py --mass 900 --proc bgth